language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- npm test
- npm run build
deploy:
  provider: heroku
  api_key:
    secure: JMGW3PTdldVLBjclrZNPmxBJU2XDml4z5A/f7TXviY9bH+d4eHY9LwQSA1qnXKo+sD0JQD2sQ7dxstULovuNvZAA8jtbn3J+WiT+Fqr1EBf/GllmXZ9vqUmrXZgOXwPxh4UmcgnG6gJM4vR7gDUTmO9CJ6iJkNaYzqlilpkZUAsDBVeeW7XpZ8Qe8i7BSN4idtOGXobvqmhX33ygKwu1ztqxQcRtbtyekGlwOHZOjiBvWvVT1KaCjyPTG/6Ja1cW8YizPqEJjus1SJPYO6XPIehLSPb4JU1PILfpwuzY98UkLpMxvNlPQB8xM2Vsta4Hn19TNRcXSyKQU7kVq+hke/x0dO2HycDUjBWcerqjNCyDsTarjCsV3/+n/gx+3zHgdbweOt+LzPAqh5cCKZXNbqisGVy59G0UVwyA1fbkxs10yLYP16yEO9caZF+VHYs6UiLEVeT/kmRSRpxanX7EJM+THo/35lPd7i1yQty7rWo9FSJCNYyUEFrMmg2PVNGo5BbZ8jiwM7jZlwGxfA5E3TseWm/mDnGQifUFX9bcozFg8/rkDazqnWv6+ROLOjYol9fNkkDef9Ak9ePPGbQx2obQkNQFmntk5uPNTVzZ1AOnGzRrdGo7YPUk0ZWgj79bdCH+iBROwXg5haggAlfFZLoLfl+SwNlD+OmRS7wGWC4=
  app: compramundo
